# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4e54fdad2fa624b6987934e1348378590ba5758755e64db8345edd94bd0a02286938442e9160fa521ac1ac3b82777a97f86d3c7dfefeaf08f83d24a1f164956a

test:
  secret_key_base: adbdef58599b71738e7e5ee344f628a7ddc36670be2fc5949013cf22368a86078fc17da54848812ef3e89b046227dab3a3658030e1c67acd5080c26d9c3a866b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
